
version: '3.9'

services:
  db:
    image: bitnami/mysql:latest
    restart: always
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: 'taskdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3307:3306"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
volumes:
  my-db:


